### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
a1 = np.array([-1,4,5],dtype=np.float16)
a1

array([-1.,  4.,  5.], dtype=float16)

In [14]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
b1 = np.array([[12,2],[1,3]])
b1

array([[12,  2],
       [ 1,  3]])

In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
c1 = np.array([[[1,3,0],[4,5,6],[0,1,8]]])
print(c1)

[[[1 3 0]
  [4 5 6]
  [0 1 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(1,6,2)

array([1, 3, 5])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [25]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random - b/w (-1,1)
np.random.random((3,4))

array([[0.85721156, 0.31248316, 0.08807828, 0.35230774],
       [0.96813914, 0.44681708, 0.56396358, 0.53020065],
       [0.03277116, 0.28543753, 0.09521082, 0.87967034]])

In [44]:
np.random.random((2,5)).reshape(5,2)

array([[0.2684227 , 0.64668116],
       [0.72084082, 0.80178733],
       [0.60394411, 0.57906473],
       [0.20105858, 0.98697378],
       [0.07292928, 0.34031059]])

In [31]:
# np.linspace - equidistant
np.linspace(-1,100,10,dtype=int)

array([ -1,  10,  21,  32,  43,  55,  66,  77,  88, 100])

In [28]:
np.linspace(1,100,50, dtype=float)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [34]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
# ndim -- no. of axes -> a3: 2*2 array, row, column
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a3.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [39]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [37]:
# itemsize --  returns the size of each element in array in bytes
a3.itemsize

8

In [42]:
a41 = np.arange(20).reshape(5, 2, 2,1).astype(np.float16)
a41

array([[[[ 0.],
         [ 1.]],

        [[ 2.],
         [ 3.]]],


       [[[ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.]]],


       [[[ 8.],
         [ 9.]],

        [[10.],
         [11.]]],


       [[[12.],
         [13.]],

        [[14.],
         [15.]]],


       [[[16.],
         [17.]],

        [[18.],
         [19.]]]], dtype=float16)

In [43]:
a41.shape

(5, 2, 2, 1)

In [44]:
a41.ndim

4

In [45]:
a41.itemsize

2

In [40]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [45]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [46]:
a3.astype(np.float32)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

### Array Operations

In [47]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
# scalar operations

# arithmetic
a1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [49]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[85., 35., 86.],
       [82., 30., 51.],
       [43., 98., 53.]])

In [50]:
a4 = np.random.random((2,5))
a4

array([[0.14131069, 0.04743729, 0.78308236, 0.12727344, 0.10803848],
       [0.95242968, 0.25687899, 0.91628086, 0.52317842, 0.47206793]])

In [56]:
a4 = np.round(a4*20)
a4

array([[  0.,   0., 160.,   0.,   0.],
       [160.,  80., 160.,  80.,  80.]])

In [57]:
a4.astype(np.int16)

array([[  0,   0, 160,   0,   0],
       [160,  80, 160,  80,  80]], dtype=int16)

In [59]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0) #multiply all elements along ROW in np.array

array([299710., 102900., 232458.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([317.55555556, 854.        ,  96.22222222])

In [58]:
# trigonomoetric functions
np.sin(a1)

array([[-0.17607562, -0.42818267, -0.92345845],
       [ 0.31322878, -0.98803162,  0.67022918],
       [-0.83177474, -0.57338187,  0.39592515]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [3]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[87., 60., 24.],
       [95., 10., 43.]])

### Indexing and Slicing

In [5]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a2[1,0]

4

In [9]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [12]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [14]:
import numpy as np
a1 = np.arange(10)

In [15]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [19]:
for i in a3:
  print(i+1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [24]:
"""
Let's break down the code and explain how the loop works.

**What does `i`, `j`, and `k` represent?**

In the context of the 3D array `a3`, `i`, `j`, and `k` represent the indices of the array along each axis:

* `i`: represents the index along the **first axis** (axis=0), which has a shape of 3.
* `j`: represents the index along the **second axis** (axis=1), which has a shape of 3.
* `k`: represents the index along the **third axis** (axis=2), which has a shape of 3.

**How does the loop work?**

The loop is a nested loop, which means that it has three levels of iteration:

1. The outermost loop iterates over the first axis (`i`): `for i in range(a3.shape[0]):`
2. The middle loop iterates over the second axis (`j`): `for j in range(a3.shape[1]):`
3. The innermost loop iterates over the third axis (`k`): `for k in range(a3.shape[2]):`

Here's the flow of the loop with the values of `i`, `j`, and `k`:

**Iteration 1**

* `i` = 0 (first axis)
	+ `j` = 0 (second axis)
		- `k` = 0 (third axis)
			- `a3[i, j, k]` = `a3[0, 0, 0]` = 0
		- `k` = 1 (third axis)
			- `a3[i, j, k]` = `a3[0, 0, 1]` = 1
		- `k` = 2 (third axis)
			- `a3[i, j, k]` = `a3[0, 0, 2]` = 2
	+ `j` = 1 (second axis)
		- `k` = 0 (third axis)
			- `a3[i, j, k]` = `a3[0, 1, 0]` = 3
		- `k` = 1 (third axis)
			- `a3[i, j, k]` = `a3[0, 1, 1]` = 4
		- `k` = 2 (third axis)
			- `a3[i, j, k]` = `a3[0, 1, 2]` = 5
	+ `j` = 2 (second axis)
		- `k` = 0 (third axis)
			- `a3[i, j, k]` = `a3[0, 2, 0]` = 6
		- `k` = 1 (third axis)
			- `a3[i, j, k]` = `a3[0, 2, 1]` = 7
		- `k` = 2 (third axis)
			- `a3[i, j, k]` = `a3[0, 2, 2]` = 8

**Iteration 2**

* `i` = 1 (first axis)
	+ `j` = 0 (second axis)
		- `k` = 0 (third axis)
			- `a3[i, j, k]` = `a3[1, 0, 0]` = 9
		- `k` = 1 (third axis)
			- `a3[i, j, k]` = `a3[1, 0, 1]` = 10
		- `k` = 2 (third axis)
			- `a3[i, j, k]` = `a3[1, 0, 2]` = 11
	+ `j` = 1 (second axis)
		- `k` = 0 (third axis)
			- `a3[i, j, k]` = `a3[1, 1, 0]` = 12
		- `k` = 1 (third axis)
			- `a3[i, j, k]` = `a3[1, 1, 1]` = 13
		- `k` = 2 (third axis)
			- `a3[i, j, k]` = `a3[1, 1, 2]` = 14

"""

for i in range(a3.shape[0]):
    for j in range(a3.shape[1]):
        for k in range(a3.shape[2]):
            print(a3[i, j, k])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [47]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [50]:
# reshape
a41

array([[[[ 0.],
         [ 1.]],

        [[ 2.],
         [ 3.]]],


       [[[ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.]]],


       [[[ 8.],
         [ 9.]],

        [[10.],
         [11.]]],


       [[[12.],
         [13.]],

        [[14.],
         [15.]]],


       [[[16.],
         [17.]],

        [[18.],
         [19.]]]], dtype=float16)

In [55]:
a41.reshape((2,10))

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]], dtype=float16)

In [53]:
a41 = a41.reshape((2,10)) # u need to assign the shape to see the reflected changes in a41
a41

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]], dtype=float16)

In [58]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [59]:
# ravel
"""
np.ravel() is a function provided by the NumPy library in Python, used to convert a multi-dimensional array into a one-dimensional array.
Unlike np.flatten(), which creates a new array, np.ravel() returns a flattened view of the original array.
"""
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [60]:
a41.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.], dtype=float16)

### Stacking

In [62]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [63]:
# horizontal splitting - done vertically
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [69]:
# vertical splitting happens horz.ly

In [67]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
np.vsplit(a5,1)

[array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]